server:
  port: 8080

mysql:
  url: tcp(127.0.0.1:3306)/slim_admin?charset=utf8mb4&parseTime=True&loc=Local
  username: root
  password:
  connection-pool:
    max-idle-conns: 20
    max-open-conns: 20
    conn-max-life-time-seconds: 3600

redis:
  addr: 127.0.0.1:6379
  password:
  db: 0